name: main

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: PHP CS Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --diff --dry-run

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: php:7.4-cli-alpine
    steps:
    - name: Set Up Container
      run: |
        # https://docs.pact.io/docker#reference-image
        apk add --no-cache --virtual build-dependencies build-base
        apk --no-cache add ca-certificates wget bash \
          && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
          && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk \
          && apk add glibc-2.29-r0.apk
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
        composer global require hirak/prestissimo > /dev/null

    - name: Checkout
      uses: actions/checkout@master

    - name: Install Dependencies
      run: composer install

    - name: Test
      run: |
        ./vendor/bin/codecept build
        ./vendor/bin/codecept run
      env:
        PACT_BROKER_URI: ${{ secrets.PACT_BROKER_URI }}
        PACT_CONSUMER_TAG: ${{ secrets.PACT_CONSUMER_TAG }}
        PACT_CONSUMER_VERSION: ${{ secrets.PACT_CONSUMER_VERSION }}
        PACT_BROKER_BEARER_TOKEN: ${{ secrets.PACT_BROKER_BEARER_TOKEN }}
